In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
import numpy as np
c=np.zeros((3,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
d=np.random.random((2,2))
print(d)

[[0.1571388  0.03752521]
 [0.88441023 0.60111338]]


In [13]:
e=np.arange(0,20,5)
print(e)

[ 0  5 10 15]


In [19]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarr=arr.reshape(4,3)
print(arr)
print(newarr)


[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [21]:
flat=arr.flatten()
print(arr)
print(flat)


[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[1 2 3 4 5 6 7 8 1 2 0 1]


In [23]:
print(arr.ndim)

2


In [25]:
print(arr.shape)

(3, 4)


In [27]:
print(arr.dtype)

int64


In [29]:
print(arr.size)

12


In [31]:
newtype=arr.astype('f')
print("\nconvert array:\n",newtype)
print('\nconverted array type:\n',newtype.dtype)


convert array:
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 0. 1.]]

converted array type:
 float32


In [37]:
size=len(arr)
print("\n size of array:\n",size)


 size of array:
 3
